### ISSUE TITLE
NumPy Information Map: Park content in md under NumPy/archive

### ISSUE THREAD

**Issue by shaloo** [numpy/archive#14]
Ref: https://docs.google.com/document/d/1tJBAv-z1QcRd2mtCME03MxBH3LYNSLa9qqmW2kg57XQ/edit?usp=sharing that was drafted for NumPy. 

For now, as suggested by @rgommers, we'll park it in archives and iterate when things change.

**Comment by shaloo** [comment]
Label: Content / Inputs for website reorg/information organisation.

**Comment by mattip** [comment]
Can we close this? The document exists.

**Comment by shaloo** [comment]
Sure. Done.
