### ISSUE TITLE
Review the .sbv file of the video "Maintaining NumPy: Deprecations"

### ISSUE THREAD

**Issue by InessaPawson** [numpy/archive#53]
Review/edit the .sbv file of the video recording of @seberg ’s presentation for NumPy Newcomers Hour (https://www.youtube.com/watch?v=DjiC4-8c5f0).
Ping @inessapawson to receive the auto-generated file.

**Comment by Bennykillua** [comment]
@InessaPawson Can I be assigned this.

**Comment by Bennykillua** [comment]
Hi @InessaPawson You can assign this task to me. Thanks

**Comment by InessaPawson** [comment]
@Bennykillua I've emailed you the file. Don't hesitate to reach out if you run into any questions.
Thank you for doing this work!

**Comment by Bennykillua** [comment]
@InessaPawson I just emailed the file to you.

**Comment by InessaPawson** [comment]
@Bennykillua I’ve reviewed the document with the subtitles. It looks great! Thank you for doing this work!
Please submit the final version of the same transcript via PR to this file https://github.com/numpy/archive/blob/main/video-transcripts/numpy-deprecations.md. It will serve as the first draft for a tutorial about deprecations in NumPy.
